# Generated by Django 5.2.8 on 2026-01-24 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('affected_plant_part', models.CharField(choices=[('leaf', 'Leaf'), ('stem', 'Stem'), ('root', 'Root'), ('fruit', 'Fruit'), ('all', 'All Parts')], max_length=20)),
                ('symptoms', models.TextField(help_text='Detailed description of disease symptoms')),
                ('causes', models.TextField(help_text='Causes and contributing factors')),
                ('prevention_methods', models.TextField(help_text='Prevention strategies')),
                ('treatment_recommendations', models.TextField(help_text='Treatment and management recommendations')),
                ('image_path', models.CharField(blank=True, help_text='Path to disease image', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Diseases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False, help_text='Whether image has been verified as accurate')),
                ('source', models.CharField(blank=True, help_text='Source of the image', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='disease.disease')),
            ],
            options={
                'verbose_name': 'Disease Image',
                'verbose_name_plural': 'Disease Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
